""" EN

DEPENDS on 04

Copy-paste your code from 04/05/06, and extend the Rectangle class with a `to_svg(self) -> str:` method, that returns the SVG string of the rectangle in this format:

<rect x="..." y="..." width="..." height="..." fill="..." />

where x and y are the coordinates of the TOPLEFT corner, fill is the color of the rectangle, width/height are the dimensions along the x/y axis.

Also implement the `write_to_svg` function below, that expects:
 - filename: where it will write an SVG file
 - width / height: the dimensions of the image
 - rectangles: a list of Rectangle objects to be written in the file. 
 a list of Rectangles, 

 
The first line of the SVG should look like:
<svg width="..." height="..." xmlns="http://www.w3.org/2000/svg">

And the last line:
</svg>

In each line between them (don't forget the new lines), the SVG string of the rectangles should be in the same order as in the provided list.

The files generated by the chessboard and fibonacci test functions should look like the files under resources/svg_output.

"""

""" DE

ABHÄNGIG VON 04

Kopiere deinen Code aus 04/05/06 und erweitere die Klasse `Rectangle` um eine Methode `to_svg(self) -> str`, die den SVG-String des Rechtecks in folgendem Format zurückgibt:

<rect x="..." y="..." width="..." height="..." fill="..." />

Dabei sind `x` und `y` die Koordinaten der LINKEN OBEREN Ecke, `fill` ist die Farbe des Rechtecks und `width`/`height` sind die Abmessungen entlang der x- bzw. y-Achse.

Implementiere außerdem die untenstehende Funktion `write_to_svg`, die erwartet:
 - `filename`: wohin die SVG-Datei geschrieben wird
 - `width` / `height`: die Abmessungen des Bildes
 - `rectangles`: eine Liste von `Rectangle`-Objekten, die in die Datei geschrieben werden sollen

Die erste Zeile der SVG-Datei soll wie folgt aussehen:
<svg width="..." height="..." xmlns="http://www.w3.org/2000/svg">

Und die letzte Zeile:
</svg>

In jeder Zeile dazwischen (neue Zeilen nicht vergessen) soll der SVG-String der Rechtecke in derselben Reihenfolge wie in der übergebenen Liste stehen.

Die von den Chessboard- und Fibonacci-Testfunktionen erzeugten Dateien sollen genauso aussehen wie die Dateien unter `resources/svg_output`.

"""



import json
import random

def is_valid_color(colorname:str) -> bool:
    with open("colors.json") as f:
        colors = json.load(f)
    return colorname.lower().strip() in colors

class Rectangle:
    __minx: float
    __maxx: float
    __miny: float
    __maxy: float
    __color: str

    def __init__(self, topleft:tuple[float,float], bottomright:tuple[float,float], color:str):
        self.__minx = topleft[0]
        self.__miny = topleft[1]
        self.__maxx = bottomright[0]
        self.__maxy = bottomright[1]
        self.__color = color if is_valid_color(color) else "black"

    def contains(self,point:tuple[float,float]) -> bool:
        return self.__minx <= point[0] <= self.__maxx and self.__miny <= point[1] <= self.__maxy

    def get_color(self) -> str:
        return self.__color     
        
    def covers(self, other:"Rectangle") -> bool:
        return self.__minx <= other.__minx and self.__maxx >= other.__maxx and self.__miny <= other.__miny and self.__maxy >= other.__maxy

    def get_random_point(self) -> tuple[float,float]:
        return random.uniform(self.__minx, self.__maxx), random.uniform(self.__miny,self.__maxy)
    
    def to_svg(self) -> str:
        return f'<rect x="{self.__minx}" y="{self.__miny}" width="{self.__maxx-self.__minx}" height="{self.__maxy-self.__miny}" fill="{self.__color}" />'

def write_to_svg(filename:str, width:float, height:float, rectangles:list[Rectangle]) -> None:
    with open(filename, "w") as f:
        f.write(f'<svg width="{width}" height="{height}" xmlns="http://www.w3.org/2000/svg">\n')
        for rectangle in rectangles:
            f.write(rectangle.to_svg()+'\n')
        f.write('</svg>\n')

# Tests     

def draw_chessboard():
    write_to_svg("chessboard.svg",400,400,[
        Rectangle((50*x,50*y),(50*x+50,50*y+50), "black" if (x+y)%2==1 else "white")
        for x in range(8) for y in range(8)
    ])

def draw_fibonacci():
    colors = ["forestgreen","crimson","royalblue","white"]

    rectangles = [Rectangle((0,0),(1,1),colors[0])]
    count = 1
    x=1
    y=1
    for _ in range(7):
        rectangles.append(Rectangle((0,y),(x,x+y),colors[count%len(colors)]))
        count+=1 
        rectangles.append(Rectangle((x,0),(2*x+y,x+y),colors[count%len(colors)]))
        count+=1
        x,y = 2*x+y,x+y
    
    write_to_svg("fibonacci.svg", x, y, rectangles)

   
if __name__ == '__main__':
    draw_chessboard()
    draw_fibonacci()