
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 5;
  public static final int BOOL = 11;
  public static final int COLON = 7;
  public static final int NUMBER = 10;
  public static final int NULL = 2;
  public static final int STRING = 9;
  public static final int EOF = 0;
  public static final int RBRACKET = 4;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int LBRACKET = 3;
  public static final int RBRACE = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NULL",
  "LBRACKET",
  "RBRACKET",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "STRING",
  "NUMBER",
  "BOOL"
  };
}

