nev = input()
nev = nev.lower()
nev = nev.replace("ö", "o")
nev = nev.replace("ő", "o")
nev = nev.replace("ó", "o")
nev = nev.replace("ú", "u")
nev = nev.replace("ü", "u")
nev = nev.replace("ű", "u")
nev = nev.replace("á", "a")
nev = nev.replace("é", "e")
nev = nev.replace("í", "i")
nev = nev.title()

print(nev)