
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OCTAVE = 3;
  public static final int error = 1;
  public static final int DURATION = 4;
  public static final int EOF = 0;
  public static final int NOTE = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NOTE",
  "OCTAVE",
  "DURATION"
  };
}

